core:
  # Comment out to make it work on your cluster
  cluster: minikube
  # ChartMuseum repository or directory holding charts
  chart_repo: stable
  # Directory where we hold configtx.yaml
  dir_config: ./examples/prod/config
  # Directory where we hold:
  # 1) cryptographic material
  # 2) genesis block and
  # 3) channel transaction
  dir_crypto: ./examples/prod/crypto
  # Directory where the Helm Chart values reside
  dir_values: ./examples/prod/helm_values
cas:
  ca:
    namespace: cas
    tls_cert: ./nephos/extras/Lets_Encrypt_Authority_X3.pem
msps:
  OrdererMSP:
    ca: ca
    namespace: orderers
    org_admin: ordadmin
  PeerMSP:
    ca: ca
    namespace: peers
    org_admin: peeradmin
orderers:
  domain: orderers.svc.cluster.local
  msp: OrdererMSP
  names:
  - ord1
  - ord2
  secret_genesis: hlf--genesis
  kafka:
    pod_num: 4
peers:
  domain: peers.svc.cluster.local
  msp: PeerMSP
  names:
  - peer1
  - peer2
  channel_name: mychannel
  channel_profile: MyChannel
  secret_channel: hlf--channel
# This is only used when we implement a Composer network
composer:
  name: hlc
  secret_bna: hlc--bna
  secret_connection: hlc--connection
