core:
  # Comment out to make it work on your cluster
  cluster: hlf-dev-bis-aks
  # ChartMuseum repository or directory holding charts
  chart_repo: stable
  # Directory where we hold configtx.yaml, and where we will save:
  # 1) cryptographic material
  # 2) genesis block and
  # 3) channel transaction
  dir_config: ./examples/dev/config
  # Directory where the Helm Chart values reside
  dir_values: ./examples/dev/helm_values
cas: #{}
  # TODO: Initially we create an example with an actual CA, later we substitute with cryptogen
  ca:
    namespace: cas
    # TODO: We should be able to set up a relative path
    tls_cert: /Users/sasha/Aid_Tech/nephos/nephos/extras/Lets_Encrypt_Authority_X3.pem
msps:
  OrdererMSP:
    # TODO: Remove dependency on CA
    ca: ca
    namespace: orderers
    org_admin: ordadmin
    # org_passwd:  # Set implicitly
  PeerMSP:
    # TODO: Remove dependency on CA
    ca: ca
    namespace: peers
    org_admin: peeradmin
    # org_passwd:  # Set implicitly
orderers:
  domain: orderers.svc.cluster.local
  msp: OrdererMSP
  names:
  - ord1
  secret_genesis: hlf--genesis
peers:
  domain: peers.svc.cluster.local
  msp: PeerMSP
  names:
  - peer1
  channel_name: mychannel
  channel_profile: MyChannel
  secret_channel: hlf--channel
# This is only used when we implement a Composer network
composer:
  name: hlc
  secret_bna: hlc--bna
  secret_connection: hlc--connection
