core:
  # Comment out to make it work on your cluster
  cluster: hlf-dev-bis-aks
  # ChartMuseum repository or directory holding charts
  chart_repo: stable
  # Directory where we hold configtx.yaml, and where we will save:
  # 1) cryptographic material
  # 2) genesis block and
  # 3) channel transaction
  dir_config: ./examples/dev/config
  # Directory where we hold crypto-material
  dir_crypto: ./examples/dev/crypto
  # Directory where the Helm Chart values reside
  dir_values: ./examples/dev/helm_values
cas: {}  # No CAs as we are using cryptogen
msps:
  OrdererMSP:
    namespace: orderers
    org_admin: ordadmin
    # org_passwd:  # Set implicitly
  PeerMSP:
    namespace: peers
    org_admin: peeradmin
    # org_passwd:  # Set implicitly
orderers:
  domain: orderers.svc.cluster.local
  msp: OrdererMSP
  names:
  - ord1
  secret_genesis: hlf--genesis
peers:
  domain: peers.svc.cluster.local
  msp: PeerMSP
  names:
  - peer1
  channel_name: mychannel
  channel_profile: MyChannel
  secret_channel: hlf--channel
